name: setup env

inputs:
  clang:
    default: 18

runs:
  using: "composite"
  steps:
    - name: install clang-${{ inputs.clang }}
      shell: bash
      run: |
        set -x

        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh ${{ inputs.clang }}
        sudo apt-get install -y \
          clang-tidy-${{ inputs.clang }} \
          libc++-${{ inputs.clang }}-dev

        sudo ln -sf $(which clang-${{ inputs.clang }}) /usr/bin/clang
        sudo ln -sf $(which clang-tidy-${{ inputs.clang }}) /usr/bin/clang-tidy

        clang --version
        clang-tidy --version

