name: check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ "*" ]
    types: [synchronize, opened, reopened, edited]
  workflow_dispatch:

env:
  CC: clang

defaults:
  run:
    # https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_iddefaultsrunshell
    shell: bash

jobs:
  buildifier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          bazel run //tools:format.check

  matrix-single-test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - bazel: latest
            clang: 18
            os: macos-latest
          - bazel: latest
            clang: 18
            os: ubuntu-latest
          - bazel: latest
            clang: 17
            os: ubuntu-latest
          - bazel: latest
            clang: 16
            os: ubuntu-latest
          - bazel: latest
            clang: 15
            os: ubuntu-latest
          - bazel: latest
            clang: 14
            os: ubuntu-latest
          - bazel: 7.x
            clang: 18
            os: ubuntu-latest
          - bazel: 6.x
            clang: 18
            os: ubuntu-latest
          - bazel: 5.x
            clang: 18
            os: ubuntu-latest

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: install clang ${{ matrix.clang }}
        uses: ./.github/actions/setup-env
        with:
          clang: ${{ matrix.clang }}

      - name: run clang-tidy
        env:
          USE_BAZEL_VERION: ${{ matrix.bazel }}
        run: |
          bazel test //test:check_misc-unused_test

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: install clang
        uses: ./.github/actions/setup-env

      - name: run clang-tidy
        run: |
          bazel test //...

  # https://emmer.dev/blog/skippable-github-status-checks-aren-t-really-required/
  # https://github.com/marketplace/actions/alls-green
  all:
    runs-on: ubuntu-latest
    if: always()
    needs:
      - buildifier
      - matrix-single-test
      - test
    steps:
    - uses: re-actors/alls-green@release/v1
      with:
        jobs: ${{ toJSON(needs) }}
