name: check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ "*" ]
    types: [synchronize, opened, reopened, edited]
  workflow_dispatch:

env:
  CC: clang

jobs:
  buildifier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - shell: bash
        run: |
          bazel run //tools:format.check

  matrix-single-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - bazel: latest
            clang: 18
          - bazel: latest
            clang: 17
          - bazel: latest
            clang: 16
          - bazel: latest
            clang: 15
          - bazel: latest
            clang: 14
          - bazel: 7.x
            clang: 18
          - bazel: 6.x
            clang: 18
          - bazel: 5.x
            clang: 18

    steps:
      - uses: actions/checkout@v4

      - name: install clang ${{ matrix.clang }}
        uses: ./.github/actions/setup-env
        with:
          clang: ${{ matrix.clang }}

      - name: run clang-tidy
        shell: bash
        env:
          USE_BAZEL_VERION: ${{ matrix.bazel }}
        run: |
          bazel test //test:check_misc-unused_test

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: install clang
        uses: ./.github/actions/setup-env

      - name: run clang-tidy
        shell: bash
        run: |
          bazel test //...

  all:
    runs-on: ubuntu-latest
    if: ${{ github.base_ref == 'main' }}
    needs:
      - buildifier
      - matrix-single-test
      - test
    steps:
    - run: true
